export type Industry =
  | "restaurant"
  | "cafe"
  | "hotel"
  | "retail"
  | "healthcare"
  | "gym"
  | "manufacturing"
  | "cleaning"
  | "other";

export const INDUSTRY_OPTIONS: { value: Industry; label: string }[] = [
  { value: "restaurant", label: "Restaurant" },
  { value: "cafe", label: "Café / Coffee Shop" },
  { value: "hotel", label: "Hotel" },
  { value: "retail", label: "Retail" },
  { value: "healthcare", label: "Healthcare / Clinic" },
  { value: "gym", label: "Gym / Fitness" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "other", label: "Other" },
];

export interface IndustryDefaults {
  department: string;
  shiftName: string;
  shiftStart: string;
  shiftEnd: string;
  shiftDays: number[];
}

export const INDUSTRY_DEFAULTS: Partial<Record<Industry, IndustryDefaults>> = {
  restaurant: {
    department: "Main Kitchen",
    shiftName: "Morning Shift",
    shiftStart: "08:00",
    shiftEnd: "16:00",
    shiftDays: [1, 2, 3, 4, 5],
  },
  cafe: {
    department: "Front of House",
    shiftName: "Opening Shift",
    shiftStart: "06:00",
    shiftEnd: "14:00",
    shiftDays: [1, 2, 3, 4, 5],
  },
  hotel: {
    department: "Housekeeping",
    shiftName: "Day Shift",
    shiftStart: "09:00",
    shiftEnd: "17:00",
    shiftDays: [0, 1, 2, 3, 4, 5, 6],
  },
};

export interface TaskTemplate {
  id: string;
  title: string;
  description: string;
  steps: string[];
  estMinutes: number;
  frequency: "daily" | "weekly";
  criticality: 1 | 2 | 3 | 4 | 5;
  requiredProof: "none" | "note" | "photo" | "dual";
  recurrence_v2: { type: "daily" | "weekly"; days_of_week?: number[] };
}

export const INDUSTRY_TASKS: Partial<Record<Industry, TaskTemplate[]>> = {
  restaurant: [
    {
      id: "r1",
      title: "Kitchen opening checklist",
      description: "Full kitchen startup: fire up equipment, verify cold storage temps, set up prep stations and confirm ingredient pars before service.",
      steps: [
        "Turn on fryers, flattop, ovens and allow 15 min warm-up",
        "Check walk-in fridge (≤4 °C) and freezer (≤-18 °C), log readings on the temp sheet",
        "Set up mise en place at each prep station — sauces, garnishes, portioned proteins",
        "Verify today's reservation count and confirm any allergy/dietary flags with FOH",
      ],
      estMinutes: 25,
      frequency: "daily",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r2",
      title: "Walk-in temperature log",
      description: "Record temperatures for every refrigeration and freezer unit to meet food-safety compliance.",
      steps: [
        "Read the digital thermometer on each walk-in door and note the value",
        "If any fridge reads above 4 °C or freezer above -18 °C, notify the head chef immediately",
        "Log all readings on the daily temp sheet and initial",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r3",
      title: "Prep station sanitization",
      description: "Sanitize all food-contact surfaces, cutting boards, and equipment between prep and service.",
      steps: [
        "Clear all cutting boards, containers and tools from prep surfaces",
        "Spray food-safe sanitizer and wipe down every prep table, slicer blade, and mixer bowl",
        "Replace disposable gloves, check sanitizer bucket concentration (≥200 ppm)",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r4",
      title: "Daily dry-goods inventory",
      description: "Count and record par levels for pantry staples so purchasing can reorder before stockouts.",
      steps: [
        "Walk the dry-store shelves and compare actual counts against par sheet",
        "Flag any item below 30 % par in red on the sheet",
        "Leave the completed par sheet on the chef's clipboard by end of shift",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 3,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r5",
      title: "Floor and drain cleaning",
      description: "Scrub kitchen floors, clean floor drains and grease traps to prevent slip hazards and pest issues.",
      steps: [
        "Sweep entire kitchen floor, moving rubber mats to clean underneath",
        "Mop with degreaser solution, paying attention to corners and under equipment",
        "Pull drain covers, remove debris, flush with hot water and replace covers",
      ],
      estMinutes: 30,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r6",
      title: "Hood and exhaust vent inspection",
      description: "Inspect grease buildup on hood filters and exhaust ducting. Flag heavy buildup for professional cleaning.",
      steps: [
        "Visually inspect all hood filters for grease saturation",
        "Remove filters that are more than 50 % coated and soak in the degreaser tank",
        "Check exhaust fan belts for wear and note any unusual vibration or noise",
      ],
      estMinutes: 20,
      frequency: "weekly",
      criticality: 3,
      requiredProof: "photo",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
    {
      id: "r7",
      title: "Waste and recycling rotation",
      description: "Empty all kitchen bins, replace liners, move full bags to the external dumpster and hose down bin area.",
      steps: [
        "Tie off and remove all full bin liners — separate food waste, recycling, and general",
        "Walk bags to the dumpster area, break down any cardboard for the recycling skip",
        "Spray and wipe bin interiors, replace with fresh liners",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r8",
      title: "Kitchen closing checklist",
      description: "Full end-of-service shutdown: equipment off, surfaces sanitized, food stored, doors secured.",
      steps: [
        "Turn off fryers, flattop, ovens and pilot lights; confirm all gas knobs are in OFF position",
        "Wrap, label and date all prep — store in walk-in with FIFO rotation",
        "Sanitize all surfaces, remove floor mats, mop with degreaser",
        "Lock the back door, set the alarm, and drop the keys in the lock-box",
      ],
      estMinutes: 30,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "r9",
      title: "Weekly deep clean — kitchen",
      description: "Intensive cleaning of areas not covered in the daily routine: behind equipment, inside ovens, underneath shelving.",
      steps: [
        "Pull equipment away from walls and clean the wall surfaces and floor behind",
        "Run oven self-clean cycle or manually degrease oven interiors",
        "Wipe down shelving inside the walk-in, check for expired product and discard",
        "Descale the dishwasher, clean spray arms and filters",
      ],
      estMinutes: 60,
      frequency: "weekly",
      criticality: 4,
      requiredProof: "photo",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
  ],

  cafe: [
    {
      id: "c1",
      title: "Espresso machine warm-up & calibration",
      description: "Power on, purge, and dial in the grinder so the first customer gets a perfect shot.",
      steps: [
        "Turn on the machine 20 min before open; run water through each group head to flush overnight residue",
        "Purge the steam wand for 5 seconds and wipe with a damp cloth",
        "Pull a test shot — aim for 18 g in, 36 g out in 25-30 s; adjust grind if needed",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c2",
      title: "Milk fridge temperature check",
      description: "Verify dairy storage temperature and check use-by dates on all open milk.",
      steps: [
        "Read the under-counter fridge thermometer — must read 2-4 °C",
        "Check every open milk carton for the marked use-by date; discard anything past date",
        "Ensure backup milk is rotated to the front (FIFO)",
      ],
      estMinutes: 5,
      frequency: "daily",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c3",
      title: "Pastry display rotation",
      description: "Swap out yesterday's pastries, stock fresh items, update labels and allergen cards.",
      steps: [
        "Remove any items baked more than 24 h ago; bag them for staff meal or discard",
        "Arrange today's delivery on the display with tongs — croissants front, muffins mid, specialty rear",
        "Update the allergen label cards if any new products are on display",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c4",
      title: "Syrup and condiment restock",
      description: "Top up syrup bottles at the bar, refill sugar caddies and restock stirrers/lids.",
      steps: [
        "Check each syrup pump bottle — refill any below the halfway mark from back stock",
        "Refill white sugar, raw sugar and sweetener caddies at the condiment bar",
        "Restock cup lids, sleeves, stirrers and napkin dispensers",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c5",
      title: "Customer area wipe-down",
      description: "Clean all customer-facing tables, chairs, window ledges and high-touch surfaces.",
      steps: [
        "Spray and wipe every table and chair, including underneath table edges",
        "Wipe window ledges, door handles, and the front-door glass",
        "Sweep and spot-mop the floor around the seating area",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c6",
      title: "Restroom check and restock",
      description: "Clean the customer restroom and ensure all dispensers are full.",
      steps: [
        "Clean toilet, sink, mirror and floor with disinfectant",
        "Refill soap dispenser, paper towels and toilet paper",
        "Empty the bin and replace the liner; initial the cleaning log on the door",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c7",
      title: "End-of-day till reconciliation",
      description: "Count the cash drawer, reconcile against POS, seal the cash bag.",
      steps: [
        "Print the POS Z-report for the day",
        "Count all notes and coins in the drawer and record the total",
        "Compare cash count to Z-report — note any variance over ±$2 on the discrepancy form",
        "Seal the cash in the deposit bag, drop in the safe and lock",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "c8",
      title: "Weekly grinder and machine descale",
      description: "Deep-clean the grinder burrs and run the descale cycle on the espresso machine.",
      steps: [
        "Remove the grinder hopper, brush out retained grounds from the burr chamber",
        "Run a cleaning tablet (Cafiza) backflush through each group head",
        "Start the machine's auto-descale cycle with the recommended descaling solution",
        "Flush 2 L of clean water through each group head after descale completes",
      ],
      estMinutes: 30,
      frequency: "weekly",
      criticality: 4,
      requiredProof: "photo",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
    {
      id: "c9",
      title: "Closing checklist",
      description: "Shut everything down, clean the bar, secure the premises.",
      steps: [
        "Turn off the espresso machine, grinder, blender and any heated display units",
        "Wash and sanitize all portafilters, steam wand tips, milk jugs and drip trays",
        "Wipe down the entire bar area, empty grounds knock-box, take out rubbish",
        "Lock front and back doors, activate the alarm",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 5,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
  ],

  hotel: [
    {
      id: "h1",
      title: "Room turnover inspection",
      description: "Final QA check on cleaned rooms before marking them available for guest check-in.",
      steps: [
        "Inspect bed-making: sheets taut, pillows fluffed, throw folded at foot of bed",
        "Check bathroom — toilet, shower, sink spotless; towels folded on rack; amenities full",
        "Test all lights, TV remote, A/C control, and check the minibar seal",
        "Vacuum any visible debris on carpet; wipe any smudges on mirrors or glass",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h2",
      title: "Lobby and reception area check",
      description: "Ensure the lobby presents a clean, welcoming first impression for arriving guests.",
      steps: [
        "Walk the lobby and pick up any litter, straighten furniture and magazines",
        "Check flowers/plants — remove dead leaves, top up water",
        "Wipe down the reception desk, bell stand, and elevator call buttons",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h3",
      title: "Linen inventory count",
      description: "Count clean linen stock per floor to ensure enough supply for expected turnovers.",
      steps: [
        "Count sheets, pillowcases, duvet covers and bath towels in each floor's linen closet",
        "Compare counts to the par sheet — flag any item below 50 % par",
        "Place a laundry request for any shortfalls before the next shift",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 3,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h4",
      title: "Minibar restock",
      description: "Replenish minibars in checked-out and stayover rooms, log consumed items for billing.",
      steps: [
        "Collect the consumption sheet from the front desk listing rooms to restock",
        "Refill each minibar to par, noting every consumed item on the charge sheet",
        "Return the completed charge sheets to front desk for guest folio posting",
      ],
      estMinutes: 25,
      frequency: "daily",
      criticality: 3,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h5",
      title: "Pool and gym equipment check",
      description: "Inspect pool chemistry, check gym equipment for damage, and ensure towels are stocked.",
      steps: [
        "Test pool water pH (7.2-7.6) and chlorine (1-3 ppm) with the test kit; adjust dosing if out of range",
        "Walk the gym floor — check cable machines for fraying, tighten any loose bolts",
        "Restock towel bins at pool and gym entrance; empty used-towel hampers",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 4,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h6",
      title: "Fire exit and safety inspection",
      description: "Weekly walk-through of all fire exits, extinguishers and emergency signage.",
      steps: [
        "Walk every fire exit route — confirm doors open freely and aren't blocked by furniture or storage",
        "Check each fire extinguisher: gauge in green zone, pin intact, inspection tag current",
        "Verify illuminated exit signs and emergency lighting are all functioning",
        "Log findings in the fire safety binder and report any issues to maintenance",
      ],
      estMinutes: 25,
      frequency: "weekly",
      criticality: 5,
      requiredProof: "dual",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
    {
      id: "h7",
      title: "Elevator and corridor inspection",
      description: "Check elevator operation, clean corridor carpets and verify hallway lighting.",
      steps: [
        "Ride each elevator — listen for unusual sounds, check button panel lights and door sensors",
        "Walk each guest-floor corridor: vacuum spots, straighten art, replace burnt-out bulbs",
        "Report any maintenance issues via the work-order system",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h8",
      title: "Guest amenity cart restock",
      description: "Prepare housekeeping carts with fresh amenities, toiletries and cleaning supplies for the next day.",
      steps: [
        "Restock shampoo, conditioner, soap and lotion bottles to par on each cart",
        "Load fresh terry sets (bath towel × 2, hand towel × 2, face cloth × 2) per expected turnover",
        "Refill cleaning caddy: glass cleaner, all-purpose spray, toilet bowl cleaner, cloths",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "h9",
      title: "Lost and found log",
      description: "Collect items found during turnover, tag and log them in the lost-and-found register.",
      steps: [
        "Gather all items from the shift's found-items bin",
        "Tag each item with room number, date and finder's name",
        "Enter every item into the lost-and-found register and store in the secure cabinet",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 2,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
  ],

  retail: [
    {
      id: "rt1",
      title: "Opening till setup",
      description: "Count and verify the opening float, load the till and power on the POS.",
      steps: [
        "Remove the cash tray from the safe and count the float — it must match the recorded amount",
        "Load the tray into the register, power on the POS terminal and log in",
        "Run a test transaction (void) to confirm card reader connectivity",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "rt2",
      title: "Stock replenishment walk",
      description: "Walk the sales floor, identify empty or low-stock shelves and refill from backroom.",
      steps: [
        "Walk each aisle with a scanner or notepad; flag any shelf below 30 % capacity",
        "Pull replenishment stock from the backroom using FIFO (oldest to front)",
        "Face all products after restocking — labels forward, neat rows",
      ],
      estMinutes: 30,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "rt3",
      title: "Fitting room reset",
      description: "Return tried-on items to the floor, tidy the fitting room area and check mirrors/lighting.",
      steps: [
        "Collect all garments from fitting rooms and sort by department",
        "Rehang items on correct hangers, return to their home section",
        "Wipe mirrors, pick up any tags or tissue paper, check light bulbs",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "rt4",
      title: "Price and signage audit",
      description: "Verify shelf-edge prices match the POS system, replace any damaged or missing labels.",
      steps: [
        "Spot-check 20 random SKUs: scan barcode and compare POS price to shelf label",
        "Replace any torn, faded or incorrect price labels",
        "Confirm promotional signage matches the current week's promo calendar",
      ],
      estMinutes: 25,
      frequency: "weekly",
      criticality: 3,
      requiredProof: "note",
      recurrence_v2: { type: "weekly", days_of_week: [2] },
    },
    {
      id: "rt5",
      title: "Customer floor sweep",
      description: "Sweep and spot-mop the sales floor, clean entrance mats and glass doors.",
      steps: [
        "Sweep or vacuum the full sales floor, including corners and under display units",
        "Spot-mop any spills or scuff marks",
        "Clean the entrance glass and shake out or replace the welcome mat",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "rt6",
      title: "Closing security check",
      description: "Secure all entrances, count the till, arm the alarm.",
      steps: [
        "Lock the front door and pull down the shutter or gate",
        "Count the till — cash must match the Z-report within ±$5; bag and drop in safe",
        "Walk the stockroom and fire exits to ensure all doors are locked",
        "Set the alarm, exit via the staff door and confirm it locks behind you",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "rt7",
      title: "Weekly stockroom audit",
      description: "Full count of backroom inventory for top-selling SKUs; reconcile against the system.",
      steps: [
        "Print the top-50 SKU list from the inventory system",
        "Physically count each SKU in the backroom and note actual vs. system count",
        "Investigate and document any variance greater than 3 units",
        "Submit the completed audit sheet to the store manager",
      ],
      estMinutes: 45,
      frequency: "weekly",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "weekly", days_of_week: [3] },
    },
    {
      id: "rt8",
      title: "Visual merchandising refresh",
      description: "Update window displays and feature tables per the weekly planogram.",
      steps: [
        "Review this week's planogram or visual directive from HQ",
        "Swap out window mannequins or featured products accordingly",
        "Ensure lighting is directed at focal products; straighten signage",
      ],
      estMinutes: 30,
      frequency: "weekly",
      criticality: 3,
      requiredProof: "photo",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
  ],

  healthcare: [
    {
      id: "hc1",
      title: "Waiting room sanitization",
      description: "Disinfect all high-touch surfaces in the patient waiting area between peak hours.",
      steps: [
        "Spray and wipe all chair armrests, magazine racks and side tables with hospital-grade disinfectant",
        "Wipe reception counter, pen cups, sign-in tablets and door handles",
        "Empty the waste bin and replace the liner; refill hand sanitizer dispensers",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "hc2",
      title: "Equipment sterilization log",
      description: "Run the autoclave cycle for reusable instruments and log the batch.",
      steps: [
        "Load instruments into autoclave pouches, seal and label with date and load number",
        "Run the autoclave cycle; verify temperature (134 °C) and pressure gauges during cycle",
        "After cycle, check the chemical indicator strip turned color, then log the batch in the sterilization register",
      ],
      estMinutes: 25,
      frequency: "daily",
      criticality: 5,
      requiredProof: "dual",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "hc3",
      title: "Medical supply stock check",
      description: "Count gloves, masks, syringes and bandages; flag anything below reorder point.",
      steps: [
        "Count each item on the supply shelf and compare to the par list",
        "Flag any item below 40 % par on the reorder form",
        "Check expiry dates — pull and quarantine anything expiring within 30 days",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "hc4",
      title: "Exam room turnover",
      description: "Clean and reset the exam room between patients.",
      steps: [
        "Strip exam table paper, wipe the table and replace with a fresh sheet",
        "Disinfect counter, sink, door handle and any equipment the patient contacted",
        "Restock gloves, cotton swabs, tongue depressors and hand sanitizer",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 5,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "hc5",
      title: "Biohazard waste disposal",
      description: "Seal and remove sharps containers and biohazard bags per OSHA protocol.",
      steps: [
        "Check each exam room sharps container — replace any that are ¾ full",
        "Seal biohazard bags, place in the designated pickup bin in the utility room",
        "Log the pickup-ready containers on the waste manifest",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "hc6",
      title: "End-of-day clinic lockup",
      description: "Secure medications, power down non-essential equipment and lock the facility.",
      steps: [
        "Lock the medication cabinet and controlled-substance safe; verify log counts match",
        "Power off exam room lights, non-essential monitors and the autoclave",
        "Arm the alarm system, lock all doors and confirm the answering service is active",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "hc7",
      title: "Weekly supply audit and reorder",
      description: "Full inventory of medical and office supplies; submit purchase orders for shortfalls.",
      steps: [
        "Print the master supply list and physically count every line item",
        "Record actual quantities in the inventory system",
        "Generate a purchase order for anything below reorder point and submit to the office manager",
        "Check the delivery schedule and confirm expected arrival dates",
      ],
      estMinutes: 40,
      frequency: "weekly",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "weekly", days_of_week: [5] },
    },
    {
      id: "hc8",
      title: "Fire extinguisher and AED check",
      description: "Inspect all fire safety and emergency medical equipment.",
      steps: [
        "Check fire extinguisher gauges — all should read in the green zone",
        "Verify AED pads are sealed and battery indicator is green",
        "Confirm first-aid kit is fully stocked; replace any used items",
      ],
      estMinutes: 15,
      frequency: "weekly",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
  ],

  gym: [
    {
      id: "g1",
      title: "Equipment safety walk-through",
      description: "Inspect every machine on the gym floor for wear, damage or safety hazards before members arrive.",
      steps: [
        "Check cable machines: look for fraying cables, cracked pulleys, loose pins",
        "Test each weight-stack selector pin — it should slide and lock smoothly",
        "Inspect benches and pads for tears; tighten any loose bolts with the Allen key set",
        "Verify emergency-stop buttons on treadmills and bikes are responsive",
      ],
      estMinutes: 25,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g2",
      title: "Locker room cleaning",
      description: "Full clean of showers, toilets, sinks and changing area — restock all dispensers.",
      steps: [
        "Scrub showers with mildew remover, rinse and squeegee glass doors",
        "Clean and disinfect toilets, urinals and sinks",
        "Mop the entire locker room floor with disinfectant",
        "Refill soap, shampoo, paper towels and toilet paper dispensers",
      ],
      estMinutes: 30,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g3",
      title: "Towel and water station restock",
      description: "Refill clean towel bins and check water cooler levels at all stations.",
      steps: [
        "Collect used towels from hampers and send to laundry (or restock from clean supply)",
        "Refill towel bins at the entrance, gym floor and pool area to full capacity",
        "Check all water coolers — replace empty jugs, wipe nozzle with sanitizer",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g4",
      title: "Closing equipment wipe-down",
      description: "Sanitize every touchable surface on every machine at end of day.",
      steps: [
        "Spray each machine's handles, pads and touchscreen with gym-safe disinfectant",
        "Wipe with a microfibre cloth — pay extra attention to grip areas",
        "Wipe free-weight handles, dumbbell racks and squat-rack J-hooks",
      ],
      estMinutes: 25,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g5",
      title: "Group fitness studio reset",
      description: "Clean the studio floor, return equipment and prepare for the next class.",
      steps: [
        "Stack all mats, return dumbbells and bands to their racks",
        "Spray and wipe the studio mirror and barre (if applicable)",
        "Sweep or mop the studio floor; check that the sound system and A/C are set correctly",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g6",
      title: "Pool chemistry test",
      description: "Test and adjust pool and spa water chemistry levels.",
      steps: [
        "Use the test kit: pH should be 7.2–7.6, free chlorine 1–3 ppm",
        "If readings are out of range, adjust chemical dosing per the chart on the pump room wall",
        "Log all readings in the pool chemistry binder with date and time",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g7",
      title: "Floor and mat cleaning",
      description: "Vacuum rubber flooring, disinfect yoga and stretching mats.",
      steps: [
        "Vacuum or sweep the entire gym floor, including under racks",
        "Spray each yoga/stretching mat with disinfectant and wipe both sides",
        "Hang mats to air-dry or stack with spacers between them",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "g8",
      title: "Monthly equipment maintenance log",
      description: "Preventive maintenance: lubricate, tension-check and document the condition of all major equipment.",
      steps: [
        "Lubricate treadmill belts and check tension per manufacturer spec",
        "Inspect bike pedals, seats and resistance mechanisms for wear",
        "Tighten all cable machine guide-rod bolts and check pulley alignment",
        "Record findings in the maintenance spreadsheet and flag anything needing a service call",
      ],
      estMinutes: 45,
      frequency: "weekly",
      criticality: 5,
      requiredProof: "dual",
      recurrence_v2: { type: "weekly", days_of_week: [1] },
    },
  ],

  manufacturing: [
    {
      id: "m1",
      title: "Pre-shift safety check",
      description: "Walk the production floor before the shift starts to confirm all safety measures are in place.",
      steps: [
        "Check that all machine guards are installed and emergency stops are unobstructed",
        "Verify PPE stations (goggles, ear plugs, gloves) are stocked at each entry point",
        "Inspect the floor for oil spills, loose cables or tripping hazards — clean up immediately",
        "Confirm the first-aid kit is fully stocked and the eyewash station flows properly",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 5,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m2",
      title: "Equipment calibration log",
      description: "Calibrate measurement instruments and production equipment at the start of each shift.",
      steps: [
        "Run calibration standards on scales, gauges and sensors per the SOP",
        "Record readings and compare to the tolerance range on the calibration sheet",
        "If any instrument is out of tolerance, tag it out-of-service and notify the supervisor",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 5,
      requiredProof: "dual",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m3",
      title: "Raw material intake log",
      description: "Receive, inspect and log incoming raw materials against the purchase order.",
      steps: [
        "Match the delivery note to the PO — verify item codes, quantities and batch numbers",
        "Visually inspect packaging for damage; reject and document anything compromised",
        "Log the accepted materials into the inventory system with batch and expiry info",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m4",
      title: "Quality control spot check",
      description: "Pull samples from the production line and run quality checks against spec.",
      steps: [
        "Pull 5 random units from the line every 2 hours",
        "Measure dimensions, weight and visual defects against the product spec sheet",
        "If any sample is out of spec, halt the line and notify the QC supervisor immediately",
        "Log all readings in the QC tracker with timestamp and batch number",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 5,
      requiredProof: "dual",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m5",
      title: "Production waste and scrap log",
      description: "Weigh and categorize production waste; record for environmental and cost tracking.",
      steps: [
        "Weigh scrap bins at each workstation using the floor scale",
        "Categorize waste as rework, recycle or disposal on the waste log",
        "Move disposal waste to the designated holding area for pickup",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m6",
      title: "End-of-shift handover notes",
      description: "Document shift output, issues encountered and anything the next shift needs to know.",
      steps: [
        "Record total units produced, rejected count and downtime minutes on the shift log",
        "Note any equipment issues, near-misses or pending maintenance requests",
        "Brief the incoming shift lead in person and hand over the signed log sheet",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m7",
      title: "Machine shutdown checklist",
      description: "Power down production equipment safely and clean the workstation for the next shift.",
      steps: [
        "Run each machine's shutdown sequence per the SOP; do not force-stop",
        "Apply lockout/tagout (LOTO) on any machine that needs maintenance",
        "Sweep the workstation floor, return tools to the shadow board",
      ],
      estMinutes: 20,
      frequency: "daily",
      criticality: 5,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "m8",
      title: "Weekly preventive maintenance round",
      description: "Lubricate, inspect and test equipment per the preventive maintenance schedule.",
      steps: [
        "Lubricate all specified grease points per the PM checklist",
        "Inspect belts, chains and bearings for wear; measure belt tension",
        "Run a test cycle on each machine after maintenance and log pass/fail",
        "Update the PM tracker and schedule any follow-up work orders",
      ],
      estMinutes: 60,
      frequency: "weekly",
      criticality: 5,
      requiredProof: "dual",
      recurrence_v2: { type: "weekly", days_of_week: [5] },
    },
  ],

  cleaning: [
    {
      id: "cl1",
      title: "Pre-shift supply cart preparation",
      description: "Stock your cleaning cart with chemicals, tools and liners before heading to the first site.",
      steps: [
        "Check spray bottles — refill all-purpose, glass cleaner and disinfectant from bulk containers",
        "Load fresh microfibre cloths (colour-coded: blue for glass, green for surfaces, red for bathrooms)",
        "Stock bin liners, toilet rolls, paper towels and gloves on the cart",
        "Verify the vacuum bag or canister isn't full; replace if more than ¾ full",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "cl2",
      title: "Client site cleaning — restrooms",
      description: "Full restroom clean per the client's SOW (scope of work) checklist.",
      steps: [
        "Clean and disinfect all toilets, urinals and sinks — inside and out",
        "Wipe mirrors, counters, dispensers and partitions",
        "Mop floor with disinfectant, paying attention to base of fixtures",
        "Refill soap, paper towels and toilet paper; initial the cleaning log",
      ],
      estMinutes: 25,
      frequency: "daily",
      criticality: 5,
      requiredProof: "photo",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "cl3",
      title: "Client site cleaning — offices and common areas",
      description: "Dust, vacuum and empty bins in office areas per the SOW.",
      steps: [
        "Empty all desk-side and kitchen bins; replace liners",
        "Dust desks, monitors, windowsills and shelves (do not move personal items)",
        "Vacuum carpets or mop hard floors; spot-clean any stains",
      ],
      estMinutes: 30,
      frequency: "daily",
      criticality: 4,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "cl4",
      title: "Trash collection and dumpster run",
      description: "Collect all waste from bins and transport to external dumpster.",
      steps: [
        "Collect tied bags from every room and hallway bin",
        "Separate recycling from general waste as per site policy",
        "Walk bags to the dumpster; hose down the bin area if spillage occurred",
      ],
      estMinutes: 15,
      frequency: "daily",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "cl5",
      title: "Equipment maintenance check",
      description: "Inspect vacuum, mop and scrubber equipment for faults before they cause downtime.",
      steps: [
        "Check vacuum hose for clogs, belt for wear, and filter for saturation",
        "Inspect mop heads — replace any that are frayed or discoloured",
        "If using a floor scrubber, check squeegee blade condition and tank for residue",
      ],
      estMinutes: 15,
      frequency: "weekly",
      criticality: 3,
      requiredProof: "note",
      recurrence_v2: { type: "weekly", days_of_week: [5] },
    },
    {
      id: "cl6",
      title: "Window and glass cleaning",
      description: "Clean interior glass surfaces, partitions and entrance doors.",
      steps: [
        "Spray glass cleaner on interior windows and partitions",
        "Squeegee in overlapping strokes; wipe edges with a lint-free cloth",
        "Clean glass entrance doors inside and out, including handles and push plates",
      ],
      estMinutes: 20,
      frequency: "weekly",
      criticality: 3,
      requiredProof: "none",
      recurrence_v2: { type: "weekly", days_of_week: [3] },
    },
    {
      id: "cl7",
      title: "End-of-shift report",
      description: "Complete the shift report documenting work done, issues found and client sign-off.",
      steps: [
        "Fill in the site checklist — tick every completed task",
        "Note any issues found (e.g. broken fixtures, pest sightings, access problems)",
        "Get the client's on-site contact to sign or initial the report",
      ],
      estMinutes: 10,
      frequency: "daily",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "daily" },
    },
    {
      id: "cl8",
      title: "Chemical inventory and SDS review",
      description: "Count chemical stock levels and verify Safety Data Sheets are up to date.",
      steps: [
        "Count all chemical containers against the inventory list",
        "Flag anything below 25 % remaining for reorder",
        "Verify the SDS binder has a current sheet for every chemical on site",
      ],
      estMinutes: 15,
      frequency: "weekly",
      criticality: 4,
      requiredProof: "note",
      recurrence_v2: { type: "weekly", days_of_week: [5] },
    },
  ],
};

export interface TimezoneGroup {
  group: string;
  offset: string;
  options: { value: string; label: string }[];
}

export const TIMEZONE_GROUPS: TimezoneGroup[] = [
  {
    group: "(GMT -10) Honolulu",
    offset: "-10",
    options: [
      { value: "Pacific/Honolulu", label: "Honolulu" },
    ],
  },
  {
    group: "(GMT -9) Anchorage",
    offset: "-9",
    options: [
      { value: "America/Anchorage", label: "Anchorage" },
    ],
  },
  {
    group: "(GMT -8) Los Angeles, Vancouver",
    offset: "-8",
    options: [
      { value: "America/Los_Angeles", label: "Los Angeles" },
      { value: "America/Vancouver", label: "Vancouver" },
    ],
  },
  {
    group: "(GMT -7) Denver, Phoenix",
    offset: "-7",
    options: [
      { value: "America/Denver", label: "Denver" },
      { value: "America/Phoenix", label: "Phoenix" },
    ],
  },
  {
    group: "(GMT -6) Chicago, Mexico City",
    offset: "-6",
    options: [
      { value: "America/Chicago", label: "Chicago" },
      { value: "America/Mexico_City", label: "Mexico City" },
    ],
  },
  {
    group: "(GMT -5) New York, Toronto, Bogotá",
    offset: "-5",
    options: [
      { value: "America/New_York", label: "New York" },
      { value: "America/Toronto", label: "Toronto" },
      { value: "America/Bogota", label: "Bogotá" },
    ],
  },
  {
    group: "(GMT -3) São Paulo, Buenos Aires",
    offset: "-3",
    options: [
      { value: "America/Sao_Paulo", label: "São Paulo" },
      { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires" },
    ],
  },
  {
    group: "(GMT +0) London, Lisbon, Reykjavik",
    offset: "0",
    options: [
      { value: "Europe/London", label: "London" },
      { value: "Europe/Lisbon", label: "Lisbon" },
      { value: "Atlantic/Reykjavik", label: "Reykjavik" },
    ],
  },
  {
    group: "(GMT +1) Paris, Berlin, Rome, Madrid, Amsterdam",
    offset: "+1",
    options: [
      { value: "Europe/Paris", label: "Paris" },
      { value: "Europe/Berlin", label: "Berlin" },
      { value: "Europe/Rome", label: "Rome" },
      { value: "Europe/Madrid", label: "Madrid" },
      { value: "Europe/Amsterdam", label: "Amsterdam" },
      { value: "Europe/Zurich", label: "Zurich" },
      { value: "Europe/Stockholm", label: "Stockholm" },
    ],
  },
  {
    group: "(GMT +2) Helsinki, Athens, Cairo, Johannesburg",
    offset: "+2",
    options: [
      { value: "Europe/Helsinki", label: "Helsinki" },
      { value: "Europe/Athens", label: "Athens" },
      { value: "Africa/Cairo", label: "Cairo" },
      { value: "Africa/Johannesburg", label: "Johannesburg" },
    ],
  },
  {
    group: "(GMT +3) Moscow, Istanbul, Nairobi",
    offset: "+3",
    options: [
      { value: "Europe/Moscow", label: "Moscow" },
      { value: "Europe/Istanbul", label: "Istanbul" },
      { value: "Africa/Nairobi", label: "Nairobi" },
    ],
  },
  {
    group: "(GMT +4) Dubai",
    offset: "+4",
    options: [
      { value: "Asia/Dubai", label: "Dubai" },
    ],
  },
  {
    group: "(GMT +5) Karachi",
    offset: "+5",
    options: [
      { value: "Asia/Karachi", label: "Karachi" },
    ],
  },
  {
    group: "(GMT +5:30) Mumbai, Delhi",
    offset: "+5:30",
    options: [
      { value: "Asia/Kolkata", label: "Mumbai / Delhi" },
    ],
  },
  {
    group: "(GMT +6) Dhaka",
    offset: "+6",
    options: [
      { value: "Asia/Dhaka", label: "Dhaka" },
    ],
  },
  {
    group: "(GMT +7) Bangkok, Jakarta",
    offset: "+7",
    options: [
      { value: "Asia/Bangkok", label: "Bangkok" },
      { value: "Asia/Jakarta", label: "Jakarta" },
    ],
  },
  {
    group: "(GMT +8) Singapore, Shanghai, Hong Kong, Perth",
    offset: "+8",
    options: [
      { value: "Asia/Singapore", label: "Singapore" },
      { value: "Asia/Shanghai", label: "Shanghai" },
      { value: "Asia/Hong_Kong", label: "Hong Kong" },
      { value: "Australia/Perth", label: "Perth" },
    ],
  },
  {
    group: "(GMT +9) Tokyo, Seoul",
    offset: "+9",
    options: [
      { value: "Asia/Tokyo", label: "Tokyo" },
      { value: "Asia/Seoul", label: "Seoul" },
    ],
  },
  {
    group: "(GMT +10) Sydney, Melbourne",
    offset: "+10",
    options: [
      { value: "Australia/Sydney", label: "Sydney" },
      { value: "Australia/Melbourne", label: "Melbourne" },
    ],
  },
  {
    group: "(GMT +12) Auckland",
    offset: "+12",
    options: [
      { value: "Pacific/Auckland", label: "Auckland" },
    ],
  },
];

// Flat list for backward compatibility
export const TIMEZONE_OPTIONS = TIMEZONE_GROUPS.flatMap((g) =>
  g.options.map((o) => ({ value: o.value, label: `${g.group}` }))
);
